<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspose.Cells" Version="26.9.0" />
    <PackageVersion Include="Aspose.Email" Version="26.9.0" />
    <!-- https://forum.aspose.com/t/cant-use-aspose-pdf-26-5-0-and-markdig-1-2-0/328597 -->
    <PackageVersion Include="Aspose.PDF" Version="26.9.0" Pinned="true" />
    <PackageVersion Include="Aspose.Slides.NET" Version="26.10.0" />
    <PackageVersion Include="Aspose.Words" Version="26.10.0" />
    <PackageVersion Include="DeterministicPdf" Version="2.2.0" />
    <PackageVersion Include="DeterministicIoPackaging" Version="1.0.1" />
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.5.0" />
    <PackageVersion Include="Microsoft.Bcl.Memory" Version="10.0.12" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.184" />
    <PackageVersion Include="ProjectFiles" Version="1.6.0" />
    <PackageVersion Include="Sbom" Version="0.3.1" />
    <PackageVersion Include="Verify" Version="33.3.2" />
    <PackageVersion Include="TUnit" Version="1.73.19" />
    <PackageVersion Include="Verify.TUnit" Version="33.3.2" />
    <PackageVersion Include="Argon" Version="0.38.2" />
    <PackageVersion Include="DiffEngine" Version="20.7.2" />
    <PackageVersion Include="EmptyFiles" Version="8.20.1" />
    <PackageVersion Include="SimpleInfoName" Version="3.2.1" />
  </ItemGroup>
</Project>
